# Generated by Django 4.2.4 on 2023-08-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypesenseAPIAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('documents:get', 'Get Documents'), ('documents:search', 'Search Documents'), ('documents:create', 'Create Documents'), ('documents:upsert', 'Upsert Documents'), ('documents:update', 'Update Documents'), ('documents:delete', 'Delete Documents'), ('documents:import', 'Import Documents'), ('collections:get', 'Get Collections'), ('collections:list', 'List Collections'), ('collections:create', 'Create Collections'), ('collections:delete', 'Delete Collections'), ('aliases:get', 'Get Aliases'), ('aliases:list', 'List Aliases'), ('aliases:create', 'Create Aliases'), ('aliases:delete', 'Delete Aliases'), ('synonyms:get', 'Get Synonyms'), ('synonyms:list', 'List Synonyms'), ('synonyms:create', 'Create Synonyms'), ('synonyms:delete', 'Delete Synonyms'), ('keys:get', 'Get Keys'), ('keys:list', 'List Keys'), ('keys:create', 'Create Keys'), ('keys:delete', 'Delete Keys'), ('debug:list', 'Debug Access'), ('metrics.json:list', 'Metrics Access')], db_index=True, help_text='The API permission', max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Typesense API permission',
                'verbose_name_plural': 'Typesense API permissions',
            },
        ),
        migrations.CreateModel(
            name='TypesenseAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='The date and time this key was created')),
                ('value', models.CharField(editable=False, help_text='The API key', max_length=64, unique=True)),
                ('description', models.CharField(blank=True, default='', help_text='Description of the API key', max_length=255)),
                ('collections', models.CharField(help_text='Comma-separated list of collections this key has access to', max_length=255)),
                ('expires_at_dt', models.DateTimeField(blank=True, help_text='The date and time at which this key expires. Will be set to 1 year from now if left blank.')),
                ('actions', models.ManyToManyField(blank=True, help_text='The API permissions', related_name='api_keys', to='django_typesense.typesenseapiaction')),
            ],
            options={
                'verbose_name': 'Typesense API key',
                'verbose_name_plural': 'Typesense API keys',
            },
        ),
    ]
